// Generated by _ops/fc_trivia_reel_2026-09-30/build_vo.py. Do not edit by hand.
import type { QuizLine } from "./ExQuiz";

export const TITLE: string[] = ["couple quiz", "what would you do if your ex did this?"];

export const LINES: QuizLine[] = [
  {
    "kind": "intro",
    "text": "Couple quiz. What would you do if your ex did this? Be honest.",
    "audio": "reels/convos/exQuiz1/00.wav",
    "voFrames": 216,
    "words": [
      {
        "w": "Couple",
        "at": 0
      },
      {
        "w": "quiz.",
        "at": 11
      },
      {
        "w": "What",
        "at": 65
      },
      {
        "w": "would",
        "at": 65
      },
      {
        "w": "you",
        "at": 71
      },
      {
        "w": "do",
        "at": 77
      },
      {
        "w": "if",
        "at": 86
      },
      {
        "w": "your",
        "at": 101
      },
      {
        "w": "ex",
        "at": 110
      },
      {
        "w": "did",
        "at": 119
      },
      {
        "w": "this?",
        "at": 128
      },
      {
        "w": "Be",
        "at": 173
      },
      {
        "w": "honest.",
        "at": 178
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you reply if your ex liked your old photo at 2 a.m.?",
    "audio": "reels/convos/exQuiz1/01.wav",
    "voFrames": 126,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 9
      },
      {
        "w": "reply",
        "at": 16
      },
      {
        "w": "if",
        "at": 29
      },
      {
        "w": "your",
        "at": 40
      },
      {
        "w": "ex",
        "at": 48
      },
      {
        "w": "liked",
        "at": 58
      },
      {
        "w": "your",
        "at": 68
      },
      {
        "w": "old",
        "at": 73
      },
      {
        "w": "photo",
        "at": 86
      },
      {
        "w": "at",
        "at": 93
      },
      {
        "w": "2",
        "at": 100
      },
      {
        "w": "a.m.?",
        "at": 109
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you go to your ex's wedding if they invited you?",
    "audio": "reels/convos/exQuiz1/02.wav",
    "voFrames": 98,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 8
      },
      {
        "w": "go",
        "at": 16
      },
      {
        "w": "to",
        "at": 22
      },
      {
        "w": "your",
        "at": 29
      },
      {
        "w": "ex's",
        "at": 34
      },
      {
        "w": "wedding",
        "at": 48
      },
      {
        "w": "if",
        "at": 55
      },
      {
        "w": "they",
        "at": 63
      },
      {
        "w": "invited",
        "at": 68
      },
      {
        "w": "you?",
        "at": 78
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you tell your partner if your ex messaged you?",
    "audio": "reels/convos/exQuiz1/03.wav",
    "voFrames": 120,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 11
      },
      {
        "w": "tell",
        "at": 21
      },
      {
        "w": "your",
        "at": 28
      },
      {
        "w": "partner",
        "at": 37
      },
      {
        "w": "if",
        "at": 44
      },
      {
        "w": "your",
        "at": 54
      },
      {
        "w": "ex",
        "at": 59
      },
      {
        "w": "messaged",
        "at": 69
      },
      {
        "w": "you?",
        "at": 82
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you keep the gifts your ex gave you?",
    "audio": "reels/convos/exQuiz1/04.wav",
    "voFrames": 98,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 8
      },
      {
        "w": "keep",
        "at": 19
      },
      {
        "w": "the",
        "at": 25
      },
      {
        "w": "gifts",
        "at": 34
      },
      {
        "w": "your",
        "at": 41
      },
      {
        "w": "ex",
        "at": 51
      },
      {
        "w": "gave",
        "at": 61
      },
      {
        "w": "you?",
        "at": 71
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you unblock your ex just to check their profile?",
    "audio": "reels/convos/exQuiz1/05.wav",
    "voFrames": 126,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 13
      },
      {
        "w": "unblock",
        "at": 31
      },
      {
        "w": "your",
        "at": 43
      },
      {
        "w": "ex",
        "at": 50
      },
      {
        "w": "just",
        "at": 62
      },
      {
        "w": "to",
        "at": 83
      },
      {
        "w": "check",
        "at": 93
      },
      {
        "w": "their",
        "at": 94
      },
      {
        "w": "profile?",
        "at": 101
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you answer if your ex called you on your birthday?",
    "audio": "reels/convos/exQuiz1/06.wav",
    "voFrames": 128,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 12
      },
      {
        "w": "answer",
        "at": 23
      },
      {
        "w": "if",
        "at": 38
      },
      {
        "w": "your",
        "at": 52
      },
      {
        "w": "ex",
        "at": 61
      },
      {
        "w": "called",
        "at": 70
      },
      {
        "w": "you",
        "at": 82
      },
      {
        "w": "on",
        "at": 88
      },
      {
        "w": "your",
        "at": 94
      },
      {
        "w": "birthday?",
        "at": 101
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you stay friends with your ex's best friend?",
    "audio": "reels/convos/exQuiz1/07.wav",
    "voFrames": 105,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 7
      },
      {
        "w": "stay",
        "at": 15
      },
      {
        "w": "friends",
        "at": 22
      },
      {
        "w": "with",
        "at": 32
      },
      {
        "w": "your",
        "at": 41
      },
      {
        "w": "ex's",
        "at": 44
      },
      {
        "w": "best",
        "at": 59
      },
      {
        "w": "friend?",
        "at": 68
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you want to know if your ex still loves you?",
    "audio": "reels/convos/exQuiz1/08.wav",
    "voFrames": 108,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 11
      },
      {
        "w": "want",
        "at": 21
      },
      {
        "w": "to",
        "at": 28
      },
      {
        "w": "know",
        "at": 34
      },
      {
        "w": "if",
        "at": 38
      },
      {
        "w": "your",
        "at": 46
      },
      {
        "w": "ex",
        "at": 54
      },
      {
        "w": "still",
        "at": 65
      },
      {
        "w": "loves",
        "at": 80
      },
      {
        "w": "you?",
        "at": 89
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you delete every photo of your ex?",
    "audio": "reels/convos/exQuiz1/09.wav",
    "voFrames": 106,
    "words": [
      {
        "w": "Would",
        "at": 0
      },
      {
        "w": "you",
        "at": 11
      },
      {
        "w": "delete",
        "at": 20
      },
      {
        "w": "every",
        "at": 32
      },
      {
        "w": "photo",
        "at": 58
      },
      {
        "w": "of",
        "at": 68
      },
      {
        "w": "your",
        "at": 80
      },
      {
        "w": "ex?",
        "at": 86
      }
    ]
  },
  {
    "kind": "q",
    "text": "Would you say hi if you saw your ex at the grocery store?",
    "audio": "reels/convos/exQuiz1/10.wav",
    "voFrames": 134,
    "words": [
      {
        "w": "Would",
        "at": 33
      },
      {
        "w": "you",
        "at": 46
      },
      {
        "w": "say",
        "at": 53
      },
      {
        "w": "hi",
        "at": 59
      },
      {
        "w": "if",
        "at": 67
      },
      {
        "w": "you",
        "at": 73
      },
      {
        "w": "saw",
        "at": 80
      },
      {
        "w": "your",
        "at": 83
      },
      {
        "w": "ex",
        "at": 89
      },
      {
        "w": "at",
        "at": 95
      },
      {
        "w": "the",
        "at": 100
      },
      {
        "w": "grocery",
        "at": 104
      },
      {
        "w": "store?",
        "at": 113
      }
    ]
  },
  {
    "kind": "outro",
    "text": "Which one got you? Send this to your bestie and compare answers.",
    "audio": "reels/convos/exQuiz1/11.wav",
    "voFrames": 144,
    "words": [
      {
        "w": "Which",
        "at": 0
      },
      {
        "w": "one",
        "at": 14
      },
      {
        "w": "got",
        "at": 23
      },
      {
        "w": "you?",
        "at": 32
      },
      {
        "w": "Send",
        "at": 65
      },
      {
        "w": "this",
        "at": 67
      },
      {
        "w": "to",
        "at": 74
      },
      {
        "w": "your",
        "at": 77
      },
      {
        "w": "bestie",
        "at": 89
      },
      {
        "w": "and",
        "at": 94
      },
      {
        "w": "compare",
        "at": 107
      },
      {
        "w": "answers.",
        "at": 118
      }
    ]
  }
];
