// Generated by _ops/fc_trivia_reel_2026-09-30/build_vo.py. Do not edit by hand.
import type { QuizLine } from "./ExQuiz";

export const TITLE: string[] = ["couple quiz", "would you be mad if your person did this?"];

export const LINES: QuizLine[] = [
  {
    "kind": "intro",
    "text": "Couple quiz. Would you be mad if your person did this? Be honest.",
    "audio": "reels/convos/madQuiz1/00.wav",
    "voFrames": 183,
    "words": [
      {
        "w": "Couple",
        "at": 0
      },
      {
        "w": "quiz.",
        "at": 10
      },
      {
        "w": "Would",
        "at": 55
      },
      {
        "w": "you",
        "at": 55
      },
      {
        "w": "be",
        "at": 64
      },
      {
        "w": "mad",
        "at": 71
      },
      {
        "w": "if",
        "at": 80
      },
      {
        "w": "your",
        "at": 87
      },
      {
        "w": "person",
        "at": 94
      },
      {
        "w": "did",
        "at": 105
      },
      {
        "w": "this?",
        "at": 114
      },
      {
        "w": "Be",
        "at": 154
      },
      {
        "w": "honest.",
        "at": 159
      }
    ]
  },
  {
    "kind": "q",
    "text": "They ate the last bite of your food.",
    "audio": "reels/convos/madQuiz1/01.wav",
    "voFrames": 81,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "ate",
        "at": 12
      },
      {
        "w": "the",
        "at": 18
      },
      {
        "w": "last",
        "at": 25
      },
      {
        "w": "bite",
        "at": 38
      },
      {
        "w": "of",
        "at": 45
      },
      {
        "w": "your",
        "at": 50
      },
      {
        "w": "food.",
        "at": 58
      }
    ]
  },
  {
    "kind": "q",
    "text": "They watched the next episode without you.",
    "audio": "reels/convos/madQuiz1/02.wav",
    "voFrames": 104,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "watched",
        "at": 14
      },
      {
        "w": "the",
        "at": 29
      },
      {
        "w": "next",
        "at": 40
      },
      {
        "w": "episode",
        "at": 50
      },
      {
        "w": "without",
        "at": 64
      },
      {
        "w": "you.",
        "at": 86
      }
    ]
  },
  {
    "kind": "q",
    "text": "They liked their ex's new post.",
    "audio": "reels/convos/madQuiz1/03.wav",
    "voFrames": 105,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "liked",
        "at": 30
      },
      {
        "w": "their",
        "at": 43
      },
      {
        "w": "ex's",
        "at": 56
      },
      {
        "w": "new",
        "at": 71
      },
      {
        "w": "post.",
        "at": 83
      }
    ]
  },
  {
    "kind": "q",
    "text": "They took an hour to reply, but were online the whole time.",
    "audio": "reels/convos/madQuiz1/04.wav",
    "voFrames": 142,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "took",
        "at": 13
      },
      {
        "w": "an",
        "at": 19
      },
      {
        "w": "hour",
        "at": 34
      },
      {
        "w": "to",
        "at": 36
      },
      {
        "w": "reply,",
        "at": 47
      },
      {
        "w": "but",
        "at": 77
      },
      {
        "w": "were",
        "at": 80
      },
      {
        "w": "online",
        "at": 88
      },
      {
        "w": "the",
        "at": 106
      },
      {
        "w": "whole",
        "at": 113
      },
      {
        "w": "time.",
        "at": 122
      }
    ]
  },
  {
    "kind": "q",
    "text": "They stole all the blankets. Every. Single. Night.",
    "audio": "reels/convos/madQuiz1/05.wav",
    "voFrames": 158,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "stole",
        "at": 17
      },
      {
        "w": "all",
        "at": 33
      },
      {
        "w": "the",
        "at": 53
      },
      {
        "w": "blankets.",
        "at": 72
      },
      {
        "w": "Every.",
        "at": 72
      },
      {
        "w": "Single.",
        "at": 107
      },
      {
        "w": "Night.",
        "at": 132
      }
    ]
  },
  {
    "kind": "q",
    "text": "They fell asleep while you were telling a story.",
    "audio": "reels/convos/madQuiz1/06.wav",
    "voFrames": 116,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "fell",
        "at": 22
      },
      {
        "w": "asleep",
        "at": 32
      },
      {
        "w": "while",
        "at": 49
      },
      {
        "w": "you",
        "at": 65
      },
      {
        "w": "were",
        "at": 71
      },
      {
        "w": "telling",
        "at": 80
      },
      {
        "w": "a",
        "at": 83
      },
      {
        "w": "story.",
        "at": 95
      }
    ]
  },
  {
    "kind": "q",
    "text": "They told their friends about your fight first.",
    "audio": "reels/convos/madQuiz1/07.wav",
    "voFrames": 152,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "told",
        "at": 11
      },
      {
        "w": "their",
        "at": 19
      },
      {
        "w": "friends",
        "at": 29
      },
      {
        "w": "about",
        "at": 39
      },
      {
        "w": "your",
        "at": 57
      },
      {
        "w": "fight",
        "at": 69
      },
      {
        "w": "first.",
        "at": 80
      }
    ]
  },
  {
    "kind": "q",
    "text": "They still have their ex's number saved.",
    "audio": "reels/convos/madQuiz1/08.wav",
    "voFrames": 105,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "still",
        "at": 10
      },
      {
        "w": "have",
        "at": 24
      },
      {
        "w": "their",
        "at": 35
      },
      {
        "w": "ex's",
        "at": 39
      },
      {
        "w": "number",
        "at": 55
      },
      {
        "w": "saved.",
        "at": 66
      }
    ]
  },
  {
    "kind": "q",
    "text": "They said \"I'm fine\" and went quiet all night.",
    "audio": "reels/convos/madQuiz1/09.wav",
    "voFrames": 144,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "said",
        "at": 13
      },
      {
        "w": "\"I'm",
        "at": 37
      },
      {
        "w": "fine\"",
        "at": 46
      },
      {
        "w": "and",
        "at": 77
      },
      {
        "w": "went",
        "at": 80
      },
      {
        "w": "quiet",
        "at": 88
      },
      {
        "w": "all",
        "at": 104
      },
      {
        "w": "night.",
        "at": 126
      }
    ]
  },
  {
    "kind": "q",
    "text": "They forgot your anniversary, but remembered their friend's birthday.",
    "audio": "reels/convos/madQuiz1/10.wav",
    "voFrames": 150,
    "words": [
      {
        "w": "They",
        "at": 0
      },
      {
        "w": "forgot",
        "at": 18
      },
      {
        "w": "your",
        "at": 31
      },
      {
        "w": "anniversary,",
        "at": 40
      },
      {
        "w": "but",
        "at": 58
      },
      {
        "w": "remembered",
        "at": 84
      },
      {
        "w": "their",
        "at": 99
      },
      {
        "w": "friend's",
        "at": 109
      },
      {
        "w": "birthday.",
        "at": 133
      }
    ]
  },
  {
    "kind": "outro",
    "text": "Which one would start a fight? Send this to your person.",
    "audio": "reels/convos/madQuiz1/11.wav",
    "voFrames": 114,
    "words": [
      {
        "w": "Which",
        "at": 0
      },
      {
        "w": "one",
        "at": 12
      },
      {
        "w": "would",
        "at": 20
      },
      {
        "w": "start",
        "at": 28
      },
      {
        "w": "a",
        "at": 34
      },
      {
        "w": "fight?",
        "at": 47
      },
      {
        "w": "Send",
        "at": 73
      },
      {
        "w": "this",
        "at": 73
      },
      {
        "w": "to",
        "at": 80
      },
      {
        "w": "your",
        "at": 83
      },
      {
        "w": "person.",
        "at": 88
      }
    ]
  }
];
