// Generated by _ops/fc_trivia_reel_2026-09-30/build_vo.py. Do not edit by hand.
import type { QuizLine } from "./PickOne";

export const TITLE: string[] = ["pick one for tonight", ""];

export const LINES: QuizLine[] = [
  {
    "kind": "q",
    "text": "Pick one for tonight. A: a slow massage. B: a shower together. C: kisses everywhere. D: phones off, just us.",
    "audio": "reels/abcd/pickShort1/00.wav",
    "voFrames": 333,
    "words": [
      {
        "w": "Pick",
        "at": 0
      },
      {
        "w": "one",
        "at": 7
      },
      {
        "w": "for",
        "at": 16
      },
      {
        "w": "tonight.",
        "at": 23
      },
      {
        "w": "A:",
        "at": 58
      },
      {
        "w": "a",
        "at": 69
      },
      {
        "w": "slow",
        "at": 75
      },
      {
        "w": "massage.",
        "at": 81
      },
      {
        "w": "B:",
        "at": 119
      },
      {
        "w": "a",
        "at": 134
      },
      {
        "w": "shower",
        "at": 151
      },
      {
        "w": "together.",
        "at": 151
      },
      {
        "w": "C:",
        "at": 191
      },
      {
        "w": "kisses",
        "at": 216
      },
      {
        "w": "everywhere.",
        "at": 218
      },
      {
        "w": "D:",
        "at": 258
      },
      {
        "w": "phones",
        "at": 282
      },
      {
        "w": "off,",
        "at": 286
      },
      {
        "w": "just",
        "at": 309
      },
      {
        "w": "us.",
        "at": 316
      }
    ]
  }
];
