// Generated by _ops/fc_trivia_reel_2026-09-30/build_vo.py. Do not edit by hand.
import type { QuizLine } from "./PickOne";

export const TITLE: string[] = ["couples edition", "pick one. no switching."];

export const LINES: QuizLine[] = [
  {
    "kind": "intro",
    "text": "Couples edition. Pick one for each. No switching.",
    "audio": "reels/abcd/pickOne1/00.wav",
    "voFrames": 130,
    "words": [
      {
        "w": "Couples",
        "at": 0
      },
      {
        "w": "edition.",
        "at": 24
      },
      {
        "w": "Pick",
        "at": 60
      },
      {
        "w": "one",
        "at": 62
      },
      {
        "w": "for",
        "at": 71
      },
      {
        "w": "each.",
        "at": 78
      },
      {
        "w": "No",
        "at": 100
      },
      {
        "w": "switching.",
        "at": 113
      }
    ]
  },
  {
    "kind": "q",
    "text": "Your perfect date night? A: dinner and drinks. B: movie night in bed. C: a spontaneous road trip. D: we don't leave the house.",
    "audio": "reels/abcd/pickOne1/01.wav",
    "voFrames": 327,
    "words": [
      {
        "w": "Your",
        "at": 0
      },
      {
        "w": "perfect",
        "at": 13
      },
      {
        "w": "date",
        "at": 26
      },
      {
        "w": "night?",
        "at": 35
      },
      {
        "w": "A:",
        "at": 67
      },
      {
        "w": "dinner",
        "at": 76
      },
      {
        "w": "and",
        "at": 86
      },
      {
        "w": "drinks.",
        "at": 95
      },
      {
        "w": "B:",
        "at": 122
      },
      {
        "w": "movie",
        "at": 148
      },
      {
        "w": "night",
        "at": 151
      },
      {
        "w": "in",
        "at": 157
      },
      {
        "w": "bed.",
        "at": 163
      },
      {
        "w": "C:",
        "at": 193
      },
      {
        "w": "a",
        "at": 211
      },
      {
        "w": "spontaneous",
        "at": 229
      },
      {
        "w": "road",
        "at": 229
      },
      {
        "w": "trip.",
        "at": 239
      },
      {
        "w": "D:",
        "at": 263
      },
      {
        "w": "we",
        "at": 275
      },
      {
        "w": "don't",
        "at": 288
      },
      {
        "w": "leave",
        "at": 296
      },
      {
        "w": "the",
        "at": 302
      },
      {
        "w": "house.",
        "at": 316
      }
    ]
  },
  {
    "kind": "q",
    "text": "Where do you love being kissed? A: lips. B: neck. C: forehead. D: everywhere.",
    "audio": "reels/abcd/pickOne1/02.wav",
    "voFrames": 248,
    "words": [
      {
        "w": "Where",
        "at": 0
      },
      {
        "w": "do",
        "at": 11
      },
      {
        "w": "you",
        "at": 17
      },
      {
        "w": "love",
        "at": 24
      },
      {
        "w": "being",
        "at": 32
      },
      {
        "w": "kissed?",
        "at": 46
      },
      {
        "w": "A:",
        "at": 79
      },
      {
        "w": "lips.",
        "at": 96
      },
      {
        "w": "B:",
        "at": 121
      },
      {
        "w": "neck.",
        "at": 140
      },
      {
        "w": "C:",
        "at": 167
      },
      {
        "w": "forehead.",
        "at": 185
      },
      {
        "w": "D:",
        "at": 209
      },
      {
        "w": "everywhere.",
        "at": 221
      }
    ]
  },
  {
    "kind": "q",
    "text": "What gets you in the mood fastest? A: a slow dance. B: a hug from behind. C: them all dressed up. D: a whispered compliment.",
    "audio": "reels/abcd/pickOne1/03.wav",
    "voFrames": 384,
    "words": [
      {
        "w": "What",
        "at": 0
      },
      {
        "w": "gets",
        "at": 11
      },
      {
        "w": "you",
        "at": 23
      },
      {
        "w": "in",
        "at": 29
      },
      {
        "w": "the",
        "at": 34
      },
      {
        "w": "mood",
        "at": 45
      },
      {
        "w": "fastest?",
        "at": 49
      },
      {
        "w": "A:",
        "at": 94
      },
      {
        "w": "a",
        "at": 111
      },
      {
        "w": "slow",
        "at": 122
      },
      {
        "w": "dance.",
        "at": 129
      },
      {
        "w": "B:",
        "at": 158
      },
      {
        "w": "a",
        "at": 175
      },
      {
        "w": "hug",
        "at": 191
      },
      {
        "w": "from",
        "at": 191
      },
      {
        "w": "behind.",
        "at": 201
      },
      {
        "w": "C:",
        "at": 238
      },
      {
        "w": "them",
        "at": 246
      },
      {
        "w": "all",
        "at": 257
      },
      {
        "w": "dressed",
        "at": 268
      },
      {
        "w": "up.",
        "at": 275
      },
      {
        "w": "D:",
        "at": 307
      },
      {
        "w": "a",
        "at": 318
      },
      {
        "w": "whispered",
        "at": 332
      },
      {
        "w": "compliment.",
        "at": 345
      }
    ]
  },
  {
    "kind": "q",
    "text": "What would you rather get tonight? A: a massage. B: a bath together. C: breakfast in bed tomorrow. D: all of the above.",
    "audio": "reels/abcd/pickOne1/04.wav",
    "voFrames": 384,
    "words": [
      {
        "w": "What",
        "at": 0
      },
      {
        "w": "would",
        "at": 25
      },
      {
        "w": "you",
        "at": 34
      },
      {
        "w": "rather",
        "at": 43
      },
      {
        "w": "get",
        "at": 51
      },
      {
        "w": "tonight?",
        "at": 62
      },
      {
        "w": "A:",
        "at": 107
      },
      {
        "w": "a",
        "at": 128
      },
      {
        "w": "massage.",
        "at": 134
      },
      {
        "w": "B:",
        "at": 151
      },
      {
        "w": "a",
        "at": 184
      },
      {
        "w": "bath",
        "at": 203
      },
      {
        "w": "together.",
        "at": 203
      },
      {
        "w": "C:",
        "at": 226
      },
      {
        "w": "breakfast",
        "at": 268
      },
      {
        "w": "in",
        "at": 275
      },
      {
        "w": "bed",
        "at": 289
      },
      {
        "w": "tomorrow.",
        "at": 292
      },
      {
        "w": "D:",
        "at": 312
      },
      {
        "w": "all",
        "at": 338
      },
      {
        "w": "of",
        "at": 358
      },
      {
        "w": "the",
        "at": 363
      },
      {
        "w": "above.",
        "at": 377
      }
    ]
  },
  {
    "kind": "q",
    "text": "Your move after a fight? A: a long hug. B: a make-out session. C: cook their favorite food. D: pretend it never happened.",
    "audio": "reels/abcd/pickOne1/05.wav",
    "voFrames": 394,
    "words": [
      {
        "w": "Your",
        "at": 0
      },
      {
        "w": "move",
        "at": 22
      },
      {
        "w": "after",
        "at": 33
      },
      {
        "w": "a",
        "at": 42
      },
      {
        "w": "fight?",
        "at": 61
      },
      {
        "w": "A:",
        "at": 89
      },
      {
        "w": "a",
        "at": 96
      },
      {
        "w": "long",
        "at": 110
      },
      {
        "w": "hug.",
        "at": 122
      },
      {
        "w": "B:",
        "at": 154
      },
      {
        "w": "a",
        "at": 175
      },
      {
        "w": "make-out",
        "at": 190
      },
      {
        "w": "session.",
        "at": 194
      },
      {
        "w": "C:",
        "at": 197
      },
      {
        "w": "cook",
        "at": 236
      },
      {
        "w": "their",
        "at": 257
      },
      {
        "w": "favorite",
        "at": 265
      },
      {
        "w": "food.",
        "at": 274
      },
      {
        "w": "D:",
        "at": 283
      },
      {
        "w": "pretend",
        "at": 319
      },
      {
        "w": "it",
        "at": 343
      },
      {
        "w": "never",
        "at": 355
      },
      {
        "w": "happened.",
        "at": 362
      }
    ]
  },
  {
    "kind": "outro",
    "text": "Comment your letters, then send this to your partner and see if you match.",
    "audio": "reels/abcd/pickOne1/06.wav",
    "voFrames": 156,
    "words": [
      {
        "w": "Comment",
        "at": 0
      },
      {
        "w": "your",
        "at": 16
      },
      {
        "w": "letters,",
        "at": 25
      },
      {
        "w": "then",
        "at": 55
      },
      {
        "w": "send",
        "at": 62
      },
      {
        "w": "this",
        "at": 67
      },
      {
        "w": "to",
        "at": 75
      },
      {
        "w": "your",
        "at": 78
      },
      {
        "w": "partner",
        "at": 86
      },
      {
        "w": "and",
        "at": 111
      },
      {
        "w": "see",
        "at": 118
      },
      {
        "w": "if",
        "at": 122
      },
      {
        "w": "you",
        "at": 127
      },
      {
        "w": "match.",
        "at": 133
      }
    ]
  }
];
